#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Print the message.

if command -V figlet > /dev/null; then
    figlet -f slant "See You Space Cowboy..."
else
    echo "See You Space Cowboy..."
fi
