#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# If we are not in a tmux session
if [ -z $TMUX ]; then
    # Display system information
    # archey
    # neofetch --ascii_bold off # --colors "\033[94"
    cal -3
    # Print a random, hopefully interesting, adage.
    if (( $+commands[fortune] )); then
      if [[ -t 0 || -t 1 ]]; then
        fortune -s | lolcat
        print
      fi
    fi
fi
